package com.example.HRMS.Entities;


import jakarta.persistence.Entity;
import jakarta.persistence.*;
import lombok.*;

import java.io.Serializable;
import java.time.LocalDate;


@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString


public class Employee implements Serializable {
    @Id
    //Need to use the value IDENTITY to generation type for MySQL to have an index that increments its value automatically
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, updatable = false)
    private Long idEmployee;
    private String nmatricule;
    private boolean sexe;
    private boolean status;
    private String nom;
    private String prenom;
    private String email;
    @Column(name = "date_embouche")
    private LocalDate dateembauche;
    @Column(name = "date_naissance")
    private LocalDate datenaissance;
    private String function;
    private String departement;
    @Column(name = "N+1")
    private String Nplusone;
    @Column(name = "N+2")
    private String Nplustwo;
    private String manager;
    private  String password;

    //empty constructor
//    Employee() {
//    }

//    //constructor with all fields except id, that is an autogenerated value
//    public Employee(String nom, String prenom, String email, String date_embauche, String date_naissance,function,domaine,teamleader,departement,manager) {
//        this.nom = nom;
//        this.prenom = prenom;
//        this.email = email;
//        this.date_embauche = date_embauche;
//        this.date_naissance = date_naissance;
//    }
//
//    //Getter and Setter
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public String getName() {
//        return name;
//    }
//
//    public void setName(String name) {
//        this.name = name;
//    }
//
//    public String getSurname() {
//        return surname;
//    }
//
//    public void setSurname(String surname) {
//        this.surname = surname;
//    }
//
//    public String getEmail() {
//        return email;
//    }
//
//    public void setEmail(String email) {
//        this.email = email;
//    }
//
//    public String getTeam() {
//        return team;
//    }
//
//    public void setTeam(String team) {
//        this.team = team;
//    }
//
//    public String getImageUrl() { return imageUrl; }
//
//    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }
//
}
